const items = [
    { title: "Echoes of Silence", tag: ["mix"], img: "../assets/work/img1.jpg" },
    { title: "Midnight Canvas", tag: ["design"], img: "../assets/work/img2.jpg" },
    { title: "Vibrant Rhythms", tag: ["music"], img: "../assets/work/img3.jpg" },
    { title: "Shadow Dance", tag: ["mix"], img: "../assets/work/img4.jpg" },
    { title: "Colorful Serenity", tag: ["design"], img: "../assets/work/img5.jpg" },
    { title: "Dream Weaver", tag: ["mix"], img: "../assets/work/img6.jpg" },
    { title: "Urban Mirage", tag: ["design"], img: "../assets/work/img7.jpg" },
    { title: "Sonic Bloom", tag: ["music"], img: "../assets/work/img8.jpg" },
    { title: "Celestial Nights", tag: ["mix"], img: "../assets/work/img9.jpg" },
    { title: "Harmony Quest", tag: ["music"], img: "../assets/work/img10.jpg" },
    { title: "Abstract Harmony", tag: ["design"], img: "../assets/work/img11.jpg" },
    { title: "Rhythm and Space", tag: ["mix"], img: "../assets/work/img12.jpg" },
    { title: "Ethereal Echoes", tag: ["music"], img: "../assets/work/img13.jpg" },
    { title: "Whispers of Twilight", tag: ["mix"], img: "../assets/work/img14.jpg" },
    { title: "Mosaic of Dreams", tag: ["design"], img: "../assets/work/img15.jpg" },
    { title: "Glimpse of Eternity", tag: ["mix"], img: "../assets/work/img16.jpg" },
    { title: "Infinite Palette", tag: ["mix"], img: "../assets/work/img17.jpg" },
    { title: "Soul's Resonance", tag: ["music"], img: "../assets/work/img18.jpg" },
    { title: "Spectral Designs", tag: ["design"], img: "../assets/work/img19.jpg" },
    { title: "Temporal Visions", tag: ["mix"], img: "../assets/work/img20.jpg" },
    { title: "Luminous Journey", tag: ["design"], img: "../assets/work/img21.jpg" },
    { title: "Melodic Horizon", tag: ["music"], img: "../assets/work/img22.jpg" },
    { title: "Eclipse of the Heart", tag: ["mix"], img: "../assets/work/img23.jpg" },
    { title: "Canvas of Sound", tag: ["design"], img: "../assets/work/img24.jpg" },
    { title: "Aurora's Whisper", tag: ["mix"], img: "../assets/work/img25.jpg" },
    { title: "Visions in Bloom", tag: ["design"], img: "../assets/work/img26.jpg" },
    { title: "Harmonious Disarray", tag: ["music"], img: "../assets/work/img27.jpg" },
    { title: "Orchestral Dreams", tag: ["music"], img: "../assets/work/img28.jpg" },
    { title: "Symphony of Night", tag: ["design"], img: "../assets/work/img29.jpg" },
    { title: "Echoing Serenade", tag: ["music"], img: "../assets/work/img30.jpg" },
    { title: "Mystical Frequencies", tag: ["mix"], img: "../assets/work/img31.jpg" },
    { title: "Serenity in Chaos", tag: ["mix"], img: "../assets/work/img32.jpg" },
    { title: "Rhythmic Illusions", tag: ["music"], img: "../assets/work/img33.jpg" },
    { title: "The Color of Sound", tag: ["design"], img: "../assets/work/img34.jpg" },
  ];
  